### ISSUE TITLE
Calls stack on connecting when on restricted network

### ISSUE THREAD

**Issue by iShift** [grishka/libtgvoip#75]
When use enterprise/captive wifi where all port instead of 443 are block - call try to connect but don't work. 

Suggestion - use 433 port or relay call with telegram server

**Comment by grishka** [comment]
Firstly, this isn't related to the library itself, but rather to the Telegram backend. For which there isn't an issue tracker ¯\\\_(ツ)\_/¯

Secondly, even if relays did support the port 443, calls use UDP. Port 53 (DNS) would _probably_ work better in such a restricted environment, but I have no idea tbh. While TCP is supported as a last resort option, you need a perfect internet connection so that there aren't delays introduced by TCP retransmissions.
